openapi: 3.0.0
info:
  title: Anki Connect Deck and Card API
  version: 1.0.0
paths:
  /createDeck:
    post:
      summary: Create a new deck
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deck:
                  type: string
                  description: The name of the new deck
              required:
                - deck
      responses:
        '200':
          description: Deck created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                    description: The ID of the created deck
                  error:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  error:
                    type: string
  /addNote:
    post:
      summary: Add a new card (note)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deckName:
                  type: string
                  description: The deck to add the note to
                modelName:
                  type: string
                  description: The model to use for the note
                fields:
                  type: object
                  description: The fields of the note
                  additionalProperties:
                    type: string
                options:
                  type: object
                  description: Optional parameters for creating the note
                  properties:
                    allowDuplicate:
                      type: boolean
                      description: Whether to allow duplicate notes
              required:
                - deckName
                - modelName
                - fields
      responses:
        '200':
          description: Note added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                    description: The ID of the created note
                  error:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  error:
                    type: string
