openapi: 3.0.0
info:
  title: Deck API
  version: 1.0.0
paths:
  /createDeck:
    post:
      summary: Create a new deck
      operationId: createDeck
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeckRequest'
      responses:
        '200':
          description: Deck created successfully
  /addCards:
    post:
      summary: Add Cards to a deck
      operationId: addCards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotesRequest'
      responses:
        '200':
          description: Cards added successfully
components:
  schemas:
    Fields:
      type: object
      properties:
        Front:
          type: string
        Back:
          type: string
    Media:
      type: object
      properties:
        url:
          type: string
        filename:
          type: string
        skipHash:
          type: string
        fields:
          type: array
          items:
            type: string
    Note:
      type: object
      properties:
        deckName:
          type: string
        modelName:
          type: string
        fields:
          $ref: '#/components/schemas/Fields'
        tags:
          type: array
          items:
            type: string
        audio:
          type: array
          items:
            $ref: '#/components/schemas/Media'
        video:
          type: array
          items:
            $ref: '#/components/schemas/Media'
        picture:
          type: array
          items:
            $ref: '#/components/schemas/Media'
    NotesRequest:
      type: object
      properties:
        notes:
          $ref: '#/components/schemas/Note'
    DeckRequest:
      type: object
      properties:
        deck:
          type: string
